DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)

-- CREATE
INSERT INTO TB_HEROES (NOME, PODER)
VALUES 
    ('Hulk', 'Poder esmagador'),
    ('Flash', 'Velocidade'),
    ('Superman', 'Voar')

-- READ
SELECT * FROM TB_HEROES;
SELECT * FROM TB_HEROES WHERE NAME='Hulk';

-- UPDATE
UPDATE TB_HEROES
SET NOME='Goku', PODER='God'
WHERE ID=1;

-- DELETE
DELETE FROM TB_HEROES WHERE ID=2